# Generated by Django 3.0.3 on 2020-03-06 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200306_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 16, 42, 25, 288756)),
        ),
    ]
